### ISSUE TITLE
Communication between groups

### ISSUE THREAD

**Issue by lefort-kara** [javydreamercsw/validation-manager#72]
Create twitter like activity feed that would combine all comments made. This would help communication between groups and allow people to bring up concerns in an organized way. This is an enhancement feature that was provided in Jama. 
![activitystream](https://user-images.githubusercontent.com/30300115/28386122-91a45fe0-6c98-11e7-9347-d3121648b3f8.png)

- [x] Implement Database Changes
- [x] Add GUI (Dashboard)
- [x] Add actions that would populate the activity stream.

**Comment by javydreamercsw** [comment]
Activity stream. It's doable for sure. It'll come down to how much information to put there. Seems doable.
