### ISSUE TITLE
Insecure password warning

### ISSUE THREAD

**Issue by lefort-kara** [javydreamercsw/validation-manager#73]
Same error occurs in both firefox and google chrome when using link [demo](http://eqvsrd00.sncorp.smith-nephew.com:7070/validation-manager/ )
[firefox error](https://support.mozilla.org/en-US/kb/insecure-password-warning-firefox?as=u&utm_source=inproduct>)
[chrome error](<https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html>)

![passworderror](https://user-images.githubusercontent.com/30300115/28388257-1b82bb2e-6ca0-11e7-929b-d13539222ab2.PNG)

**Comment by javydreamercsw** [comment]
Thanks, will look into it.

**Comment by javydreamercsw** [comment]
This might help: https://vaadin.com/blog/-/blogs/enabling-https-in-your-java-server-using-a-free-certificate

**Comment by javydreamercsw** [comment]
This is controlled by the server hosting the application itself. For example for Tomcat this would be an [example](https://www.mulesoft.com/tcat/tomcat-ssl) on how to do it. 

I'll add a Wiki page for this and close the issue.

**Comment by javydreamercsw** [comment]
See [wiki page](https://github.com/javydreamercsw/validation-manager/wiki/Using-SSL)
