### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by lefort-kara** [javydreamercsw/validation-manager#85]
Steps to reproduce:
1. Go to http://eqvsrd00.sncorp.smith-nephew.com:7070/validation-manager/
The below screen appears.
![image](https://user-images.githubusercontent.com/30300115/28936445-c6542806-7855-11e7-89f9-87b968b06e83.png)

2. Attempt to login with admin.
![image](https://user-images.githubusercontent.com/30300115/28936492-e9c0b19c-7855-11e7-8c54-e7e2bd8f7d41.png)

The pages does not load correctly, the login popup is still present. There is no demo data displayed.

**Comment by javydreamercsw** [comment]
Reopened issue #76 to continue investigation.
As a workaround don't log in with multiple windows open.
